# Generated by Django 3.2.3 on 2021-05-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210531_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phoneModel',
        ),
    ]
